# MQTT
mqtt:
  broker: 192.168.10.167
  username: ${mqtt_username}
  password: ${mqtt_password}
  log_topic: ${device_name}/logs
  reboot_timeout: 0s

# OTA Updates
ota:
  - platform: esphome
    password: ${ota_password}

# Web Server
web_server:
  version: 3
  port: 80
  auth:
    username: ${web_server_username}
    password: ${web_server_password}

logger:

prometheus:

sensor:
  - platform: uptime
    name: "Uptime"
    id: uptime_sensor
    update_interval: 20s
    entity_category: "diagnostic"
