# # MQTT
# mqtt:
#   broker: ${mqtt_broker_ip}
#   username: ${mqtt_username}
#   password: ${mqtt_password}
#   log_topic: ${device_name}/logs
#   reboot_timeout: 0s

# Enable logging
logger:

#  Home Assistant API
api:
  encryption:
    key: ${api_key}

# OTA Updates
ota:
  - platform: esphome
    password: ${ota_password}

captive_portal:

# Web Server
web_server:
  version: 3
  port: 80
  auth:
    username: ${web_server_username}
    password: ${web_server_password}

# Enable logging
logger:

# Prometheus Exporter
prometheus:

# Uptime Sensor
sensor:
  - platform: uptime
    name: "Uptime"
    id: uptime_sensor
    update_interval: 20s
    entity_category: "diagnostic"
