esphome:
  name: ${device_name}
  friendly_name: ${device_name}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf  

logger:

output:
  - platform: ledc
    pin: GPIO5
    frequency: 1000 hz
    id: pwm_outputg22
    max_power: 0.50
    # inverted: true

binary_sensor:
  - platform: gpio 
    id: button   
    pin:
      number: GPIO41
      mode:
        input: true
        pullup: true
    on_press:
      - light.toggle: led_strip
  - platform: status
    name: "Status"

light:
  - platform: monochromatic
    output: pwm_outputg22
    default_transition_length: 0.5s
    gamma_correct: 1.0
    name: "LED Strip"
    id: led_strip
