esphome:
  name: ${device_name}
  friendly_name: ${device_name}

esp8266:
  board: esp12e
  early_pin_init: false
  restore_from_flash: false # Set to true to use one of the switch's RESTORE_X restore_mode options

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Sonoff S31 Status"

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_OFF # Powering the relay may cause damage or instability when the programmer is supplying Vcc.

status_led:
  pin:
    number: GPIO13
    inverted: True
